-keep class ir.mahdiparastesh.migratio.data.Country { <fields>; }
-keep class ir.mahdiparastesh.migratio.data.Criterion { <fields>; }
-keep class ir.mahdiparastesh.migratio.data.MyCriterion { <fields>; }
